# Generated by Django 3.2.14 on 2022-10-29 10:51

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=200)),
                ('vinculacion', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('notas', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'participante',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Convocatoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreconvocatoria', models.CharField(max_length=200)),
                ('tiempo', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'convocatoria',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombredepartamento', models.CharField(max_length=200)),
                ('correo', models.EmailField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'departamento',
            },
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreinstitucion', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('pais', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'institucion',
            },
        ),
        migrations.CreateModel(
            name='PartnershipAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=40)),
                ('fecha_creacion', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'partnership_agreement',
            },
        ),
        migrations.CreateModel(
            name='Periodicidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_periodicidad', models.CharField(max_length=40)),
                ('periodosanuales', models.IntegerField()),
                ('fecha_creacion', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'periodicidad',
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'periodo',
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreprograma', models.CharField(max_length=200)),
                ('fecha_creacion', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'programa',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('proyecto_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreproyecto', models.CharField(max_length=200)),
                ('sigla', models.CharField(blank=True, max_length=10, null=True)),
                ('id_referencia', models.IntegerField(blank=True, null=True)),
                ('web', models.CharField(blank=True, max_length=100, null=True)),
                ('notas', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha_fin', models.DateField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_creacion', models.DateField(auto_now_add=True, null=True)),
                ('coordina_institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ori.institucion')),
                ('partnership_agreement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ori.partnershipagreement')),
                ('periodicidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ori.periodicidad')),
            ],
            options={
                'db_table': 'proyecto',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolename', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=200)),
                ('periodo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ori.periodo')),
                ('rol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ori.rol')),
            ],
            options={
                'db_table': 'timesheet',
            },
        ),
        migrations.CreateModel(
            name='Subprograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombresubprograma', models.CharField(max_length=200)),
                ('fecha_creacion', models.DateField(auto_now_add=True, null=True)),
                ('hijoprograma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programahijo', to='ori.programa')),
                ('hijosubprograma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subprogramahijo', to='ori.subprograma')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programapadre', to='ori.programa')),
            ],
            options={
                'db_table': 'subprograma',
                'unique_together': {('id', 'programa')},
            },
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organismo_financiador', models.CharField(blank=True, max_length=100, null=True)),
                ('total', models.CharField(blank=True, max_length=100, null=True)),
                ('presentacion', models.DateField(blank=True, null=True)),
                ('proyecto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ori.proyecto')),
            ],
            options={
                'db_table': 'presupuesto',
            },
        ),
        migrations.AddField(
            model_name='periodo',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ori.proyecto'),
        ),
        migrations.CreateModel(
            name='ParticipanteProyectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ori.proyecto')),
            ],
            options={
                'db_table': 'participante_proyectos',
                'unique_together': {('participante', 'proyecto')},
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='archivos/')),
                ('file_proyecto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ori.proyecto')),
            ],
            options={
                'db_table': 'file',
            },
        ),
        migrations.CreateModel(
            name='ConvocatoriaConvocatoriasSubprogramas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ori.convocatoria')),
                ('subprograma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ori.subprograma')),
            ],
            options={
                'db_table': 'convocatoria_convocatorias_subprogramas',
                'unique_together': {('convocatoria', 'subprograma')},
            },
        ),
        migrations.AddField(
            model_name='participante',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ori.departamento'),
        ),
        migrations.AddField(
            model_name='participante',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='participante',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='Sepresenta',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('convocatoriasubprogramas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ori.convocatoriaconvocatoriassubprogramas')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ori.proyecto')),
            ],
            options={
                'db_table': 'sepresenta',
                'unique_together': {('convocatoriasubprogramas', 'proyecto')},
            },
        ),
        migrations.CreateModel(
            name='ProyectoParticipaInstitucion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ori.institucion')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ori.proyecto')),
            ],
            options={
                'db_table': 'proyecto_participa_institucion',
                'unique_together': {('proyecto', 'institucion')},
            },
        ),
        migrations.CreateModel(
            name='Posee',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('participanteproyectos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ori.participanteproyectos')),
                ('timesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ori.timesheet')),
            ],
            options={
                'db_table': 'posee',
                'unique_together': {('participanteproyectos', 'timesheet')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='periodo',
            unique_together={('id', 'proyecto')},
        ),
    ]
