# Generated by Django 3.2.14 on 2022-10-31 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ori', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='organismo_financiador',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='total',
            field=models.CharField(max_length=100),
        ),
    ]
