# Generated by Django 3.2.14 on 2022-10-31 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ori', '0002_auto_20221031_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posee',
            name='timesheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ori.timesheet', unique=True),
        ),
    ]
