# Generated by Django 3.2.14 on 2022-11-01 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ori', '0003_alter_posee_timesheet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periodo',
            name='tiempo',
        ),
        migrations.AddField(
            model_name='timesheet',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='dia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='intelectal_output',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='lugar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='num_horas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posee',
            name='timesheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ori.timesheet'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='periodo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ori.periodo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='rol',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ori.rol'),
            preserve_default=False,
        ),
    ]
