# Generated by Django 3.2.14 on 2022-11-01 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ori', '0004_auto_20221101_0944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timesheet',
            old_name='intelectal_output',
            new_name='intellectual_output',
        ),
        migrations.AlterField(
            model_name='posee',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='proyectoparticipainstitucion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sepresenta',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='subprograma',
            name='nombresubprograma',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
