# Generated by Django 3.2.14 on 2022-11-01 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ori', '0005_auto_20221101_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='num_periodo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
