# Generated by Django 3.2.14 on 2022-11-02 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ori', '0006_periodo_num_periodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posee',
            name='timesheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ori.timesheet', unique=True),
        ),
        migrations.AlterField(
            model_name='sepresenta',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ori.proyecto', unique=True),
        ),
    ]
