# Generated by Django 3.2.14 on 2022-11-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ori', '0007_auto_20221102_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='nombretimesheet',
            field=models.CharField(default='timeseee', max_length=200),
            preserve_default=False,
        ),
    ]
