# Generated by Django 3.2.14 on 2022-11-03 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ori', '0009_auto_20221103_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posee',
            name='timesheet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ori.timesheet'),
        ),
        migrations.AlterField(
            model_name='sepresenta',
            name='proyecto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ori.proyecto'),
        ),
    ]
