# Generated by Django 3.2.14 on 2022-11-03 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ori', '0010_auto_20221103_1136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subprograma',
            old_name='hijoprograma',
            new_name='padreprograma',
        ),
        migrations.RenameField(
            model_name='subprograma',
            old_name='hijosubprograma',
            new_name='padresubprograma',
        ),
    ]
