# Generated by Django 3.2.14 on 2022-11-04 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ori', '0011_auto_20221103_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='nombretimesheet',
        ),
    ]
