# Generated by Django 3.2.14 on 2022-11-04 12:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ori', '0012_remove_timesheet_nombretimesheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='convocatoria',
            name='anio',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
