# Generated by Django 3.2.14 on 2022-11-04 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ori', '0013_convocatoria_anio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convocatoria',
            name='anio',
        ),
        migrations.RemoveField(
            model_name='convocatoria',
            name='tiempo',
        ),
    ]
