# Generated by Django 3.2.14 on 2022-11-04 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ori', '0014_auto_20221104_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convocatoria',
            name='nombreconvocatoria',
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='anio',
            field=models.IntegerField(default=2020),
            preserve_default=False,
        ),
    ]
