# Generated by Django 3.2.14 on 2022-11-05 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ori', '0017_tarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='timesheet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ori.timesheet'),
            preserve_default=False,
        ),
    ]
