# Generated by Django 3.2.14 on 2022-11-05 17:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ori', '0018_auto_20221105_0120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timesheet',
            old_name='num_horas',
            new_name='num_working_days',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='dia',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='lugar',
        ),
        migrations.AddField(
            model_name='tarea',
            name='dia',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarea',
            name='lugar',
            field=models.CharField(default='granada', max_length=200),
            preserve_default=False,
        ),
    ]
