# Generated by Django 3.2.15 on 2022-11-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ori', '0020_alter_file_file_proyecto_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='username',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
