# Generated by Django 3.2.15 on 2022-11-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ori', '0021_alter_participante_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='nombredepartamento',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
